return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 52,
  height = 52,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 10,
  nextobjectid = 489,
  properties = {},
  tilesets = {
    {
      name = "Tileset",
      firstgid = 1,
      filename = "Tileset.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 8,
      image = "Tileset.png",
      imagewidth = 128,
      imageheight = 64,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {
        {
          name = "Walls",
          tile = 0,
          properties = {}
        }
      },
      tilecount = 32,
      tiles = {
        {
          id = 0,
          terrain = { -1, -1, -1, 0 }
        },
        {
          id = 1,
          terrain = { -1, -1, 0, 0 }
        },
        {
          id = 2,
          terrain = { -1, -1, 0, -1 }
        },
        {
          id = 3,
          terrain = { 0, 0, 0, -1 }
        },
        {
          id = 4,
          terrain = { 0, 0, -1, -1 }
        },
        {
          id = 5,
          terrain = { 0, 0, -1, 0 }
        },
        {
          id = 8,
          terrain = { -1, 0, -1, 0 }
        },
        {
          id = 9,
          terrain = { 0, 0, 0, 0 }
        },
        {
          id = 10,
          terrain = { 0, -1, 0, -1 }
        },
        {
          id = 11,
          terrain = { 0, -1, 0, -1 }
        },
        {
          id = 13,
          terrain = { -1, 0, -1, 0 }
        },
        {
          id = 16,
          terrain = { -1, 0, -1, -1 }
        },
        {
          id = 17,
          terrain = { 0, 0, -1, -1 }
        },
        {
          id = 18,
          terrain = { 0, -1, -1, -1 }
        },
        {
          id = 19,
          terrain = { 0, -1, 0, 0 }
        },
        {
          id = 20,
          terrain = { -1, -1, 0, 0 }
        },
        {
          id = 21,
          terrain = { -1, 0, 0, 0 }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 52,
      height = 52,
      id = 1,
      name = "Floor",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztWFEOhTAI8wLeQO9/TX/N4lgLZfjBR/OMeetWCmR4HsdxNhoNOa4Bs/e7sEvPvfid/Y9Zu1OPVwu6tkKPBUtDRb7dTr7x3CreiJ6v80TjEeVV+cPmBerP7nxjexHiT4RXoWe158wHyx8vr6p+0D6G+oNyq/oGyufxB4l7tj8ePYxv3nhG/WHyDfFn1sd2+WNpUdRPtT9Wv0b729/8YeIbXa/2h13njXNVf7PW3cNzJC5qf1C897+GZ4Qr05+vcyJ3k9XMg8yhWf4wWpRzaHb9RPKNyd1d9VPRD/7S36x6yo4nyxfNl8r+htwPMu87Vf5k3Ucr728Z80JFf4v6w/Kq/WH0MDq98fT6swLzPYTlVOp58yq/V7F3JqUez74r3xjOinxj/UGhrJ9I/kbPk1U/VefJ6m+qfPHka2Y/mL1n5lWm7qv0oOf0zKdVepTI0tNoNBqNRhYeD1nIxA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 52,
      height = 52,
      id = 3,
      name = "Decorations",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztmc0OhCAMhLnpTd//aXcPa5Y0UMu0/KT0S0gIsWVHZ6FKSkEQ9OD8tvvXTmb87tRq86M8eZ68pfHelOZH8aaHeizvS/x2ZTGXYHyE30p9bbw2L4pnPZwvah6TaEDyoqz0TKzWN03Myno4X7R6TJsXRXpPWzVo86Lsoofuc1q/1fbNUXq4egd9JrW6iotpZRc9XP1Ga7NaX1KnzVoPKM/vLeVr2edX0SNds3rNL8mH1Fkr+w3lSjKPjV4PUFbV481v3tYDz+u19X56kP7b/Cgj650j/XVJY1rZRY/1+8Jsv0mvQ59V63VSPOvx9j0EibH8b4cePofl915tLhTLezoj3jrf7HhKr/Ms2rhz2lIfJa9rpPUOyts8Vn7zpGfUeb10niAIgiBYlQ9ErCEF"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 52,
      height = 52,
      id = 2,
      name = "Walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztWotqwzAMdLutUDYGzdb+/6cuhhrMoZMfUuyGRWBKHVuK/Dif5IRwyN7ktJYzlDv8Yt0dnmE9a3NW+mK7WN46/Pley/taPtayPH9juTzrF6jPywLPpXZYh+1RR6qP9r86/ZH6XTv1eUl8r8+OflfSj/k5Snrts3lgfo6SXvuvOj+9/rB1GvX9hjI2MRw6KfUSfiLWPYLversFjlWIgy3rNelFXYh5F9K/1x9rf+t67cU3q10NT6z+eK63Frts/82aHwsua+exRW/veDC7Oa9LuCbhFRsPVp/05tjWorck2npB/vZD2rXsn1uox8de/sb8qRkf63nM+lvOUwveWsfDe/9Z/bHOjzc+Ws+PuB+kfcXqUazjiaKNb+RvWqxZEz8iX0M9jKd5r7eEQ1L8mHhWzfjneqS4lvE07/kZJa3nV0lm+6Px2b3644lvs+NQbb15+pPjkpR/a8E3KadXikO9/Un8TcqzteKblrtj+ObN32rHR8sT1Myfdp568msrX6l9H+98psYPRrzPKP7WMj9WPusd/7D3yfNvLD5tjV8SbqYykr8htkl41rr/EO+YXu/11tJ/i3yxN15b7XrkjWbkq7b0Z0a8sJd8opR/a7kHwPiW3ccyHmi5/6nhb9IdgJaXy3EM+9Xck27Bd0bERSPzO6P88T5Pt9jPtbIF3/HMt862n+5J8buOR+D4xPJp0v9SfW7nDPZ7/EGepn3ToeXRSt+DaHk8CfsYbh5yyCGH/Af5A/vjHjo="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "Bounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 160,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 128,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 448,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 320,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 416,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 416,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 320,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 128,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 448,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 512,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 512,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 224,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 224,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 608,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 224,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 224,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 608,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 128,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 32,
          width = 576,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 704,
          width = 576,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 32,
          width = 32,
          height = 704,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 32,
          width = 32,
          height = 704,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 640,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 416,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 640,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 64,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "Bottle",
      visible = true,
      opacity = 1,
      offsetx = -8,
      offsety = -8,
      properties = {},
      objects = {
        {
          id = 387,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 448,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 496,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 624,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 432,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 466,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 624,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 432,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 481,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 482,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 483,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 484,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 486,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 487,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 624,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Blue",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 360,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 544,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 370,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 371,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 544,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 640,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 375,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 378,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 544,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 640,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 544,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 400,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 352,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Exit",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 464,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "Pink",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
