return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 70,
  height = 70,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 10,
  nextobjectid = 775,
  properties = {},
  tilesets = {
    {
      name = "Tileset",
      firstgid = 1,
      filename = "Tileset.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 8,
      image = "Tileset.png",
      imagewidth = 128,
      imageheight = 64,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {
        {
          name = "Walls",
          tile = 0,
          properties = {}
        }
      },
      tilecount = 32,
      tiles = {
        {
          id = 0,
          terrain = { -1, -1, -1, 0 }
        },
        {
          id = 1,
          terrain = { -1, -1, 0, 0 }
        },
        {
          id = 2,
          terrain = { -1, -1, 0, -1 }
        },
        {
          id = 3,
          terrain = { 0, 0, 0, -1 }
        },
        {
          id = 4,
          terrain = { 0, 0, -1, -1 }
        },
        {
          id = 5,
          terrain = { 0, 0, -1, 0 }
        },
        {
          id = 8,
          terrain = { -1, 0, -1, 0 }
        },
        {
          id = 9,
          terrain = { 0, 0, 0, 0 }
        },
        {
          id = 10,
          terrain = { 0, -1, 0, -1 }
        },
        {
          id = 11,
          terrain = { 0, -1, 0, -1 }
        },
        {
          id = 13,
          terrain = { -1, 0, -1, 0 }
        },
        {
          id = 16,
          terrain = { -1, 0, -1, -1 }
        },
        {
          id = 17,
          terrain = { 0, 0, -1, -1 }
        },
        {
          id = 18,
          terrain = { 0, -1, -1, -1 }
        },
        {
          id = 19,
          terrain = { 0, -1, 0, 0 }
        },
        {
          id = 20,
          terrain = { -1, -1, 0, 0 }
        },
        {
          id = 21,
          terrain = { -1, 0, 0, 0 }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 70,
      height = 70,
      id = 1,
      name = "Floor",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztl11uwzAMg3uB3WC5/zX3OhT6ISkqzQY/CAEaV7bpT5Tz9Xq9vk6cOGGP70G48nwb8yhr73S5gmf0W5T7GuTJdGHydE9Vlypf9i7SRckT6aLkYbRBdMk0reIKdFHzvOui5Nmqo4iBTseMF9TXEF4+7buMLh0vk3mfpAvCrcoLkucv1FHn3ywvSJ7q92xdU+9Fdem0QXRx8dKtR9Uku2N0ukzryMlLFI762vItlZeuH7P1PvXRDV1YXhz9eLovZT6VR4SX7I6M+IujlqZ8Kv6F8PJ+D0bqK1sPuk7Gz1C+VE9386L2aacuqs9v8eK8103raNq/tnhR1+PyXYcuG7w4dWF5cd6XOh9QeXHVlct3q3eKJ6q8KGfg+g6ovH2qTbRPhRf1TLJ1ILpkWjhjwku1HvW+N/Fvl/chPojysu3TyLq38k946fK41lfxyYxn6miDF1cdRTVafQd141G/2+LF7btoT0PGo316u39P+3THITs+q0fH/qf3PeVeN/FLVHc3L4yPqrxs5d/khdFF5QWtI4Rnlhek7iZ9Rz3PSh+0LrL1ILxEvawbXz2nvHWaOHjpxke9rNJd6TsqL0wddfMqfCF1wATqZ3f5KMrXVmzx4ph3ovumLq59Kpx24++K6f0H2Sfra1lvqMYgHqr8Z4sXtQ869jXRtTq3CS9XMMekjhw1ocQmL9teqZyby48nvHxaF0c/c/Hyu16j/C6u2Vpi/38XL9l63z0A9enqP0h/eX/v/D7KeEF0QTRB7kfT78ALmM/FC1tHd/SvbJ/ofFu8sPqy5zT10U/xwurLnhOjS7X/O3hhoju/aUx4ifIoPP7+nbnXM3nc9/puP4wuaB+svB/pxw5tnsKLi/dpsPvf4uUp4eJFmTfK/5Rw8TI9j6cEWodq/2PP41NPRhel/6m6PE2bTJdJ/1N1eVKw61PHnzhx4sSJEydOnPg/8QMugY2R"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 70,
      height = 70,
      id = 3,
      name = "Decorations",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztW0EOwyAM6227df9/7XapVlWkxCQO2YglJA40UGMDhbJthUKBgf2TXoNpTxbnLj0v+R5eijKaZzPE6eG5ffnpIcP7ZOdFo+FdeHZWnAgfoTxq8uw4LBQvbUi6lXSHvo8lDmtuOntYwl2ftMapkfxoHBas89HKvEha9fRRK496x7r2k+Y/L1i108uj9WrB1uQqvKCa1KzHLHmrj1D/S7BoapZ2ekDGeQnFSxsaDWfz1F1i+OgftTMat3jpl2fsuXl5zfqthK7rPPsEqSuLdixlvPBLvLC+R5jzl+RTbTs1+wwSWH3Vi59FUxJW50XjI8acxeDC00fo2Gzpkywa8ZqPVueF4amM3mFowav8TI0UL+PPS5pEv9e9zok8z2c1sSTclUHPN7zPQ1gaKV586rb6qJW3eMH67RPZJ9HjJYpZWl2dF3SNp5lfWP8nRPooYlxko3hpg81L5J6eZx1e67qZ46UEr3YULz5xUF6u671RXWvjsPc4JKC8HO+h+Qe2VxcaJ8OcUrxgeUn/6DnsiB81nopc12Ucv0d0jrQjWxwtMvCS5R6EZQ9d2geRwOjbrBoZvWdTvPTjZLmX53X+xL5/FA32+IrWmwUZeInYT5PS45I/t6nVPnT+i7wP643H9uXnwMHB3b8ZWo1E3Yf1RiZeZnpH66Ozd3pzFnqfqlAoFAqFQqHwP3gDUvlPzw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 70,
      height = 70,
      id = 2,
      name = "Walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztWwFu2zAMdLu2QLehwLo2/3/qEmAGBJZH8ZijZmAmIGRzZImRZZ7uyG7baTN7uLbHa/t0Pr1rj8lm70djfZpx0RzeeNEc3jjonm/Ourxe29O1PV/bu2nPpr0Hny9/x/Hutf3RXOM49j7bLxrL6xfN98NZlzdwnTXVOK+icbJ28/sn8MO7Xhn/SOvLzNe5LqrnjPzsMvT7VX6oxln9HkXr4vlxwymEQ178zoxjMQfhgOfnjptZ7ETYZvtewHzo+fzafCxA8Tta9x2nRox6Cfp71z1/EC55/0e4FP0eZt8iv9nr3e911li/kaF1ZH8/O06Xofef3S+of/T72f21Ou4qng/ym1131XO616J9/rF95RyIa6D4rXqPdn88juThl8WpyHeEf8iPiB95n7/J8dn1Qv5482ZxiuVB3ee6aB918rWsH2xcqMzLnmuY/vdaZd927xcmvnaui+K5sca+L93+ZP1gn+cY5xG3GK+xPIP10+qKGW1w/P4S+MGsyx7nZ7rZ2AfhBYtfEW7OtD+EoSoc7bZKnF4Zd1afu2fzrn5+R+Eju6nijsIPJi52m+p8rPBjxo9sfI/4iJf3yfCrGX6xcech8NPLN1ktL8Ipy0f2OO/Fb6u/ZfJNHkYgvY6NuzO90fphfWb1R2RK3V/B4+6Njyo8Uq0Le57qyvOo8E/Jv9nf33HOYHERmTJPpIi7iv1SzR+NDeEI6o9wTaVL3K6PeBphJJOviviRhzFR3ueJ7I/mRTiI8kqzuoVKvqqie6v2/8p4r8rvIFOuiyIPwdzfmcdS8RpVfiZr3fkalX5ceY9W4k6kj3mcAvGJyj4d81ZR3dyOgzavhGr2EP6p8hVenRviTeh5IHxB9RKzWgTEc2b5rcp+PkJc7DaVLl/hk/9CD81apX6gs/7jKFbBCwV/X123wlqFjzHxaMSpsY14kdHuUJ4nW4c3q7fz9EFVXcEsjzOrCY/62PpwNi/1tn31I+JJkT6oOHd063VZU+FlJU/cmVe5F78qOqNiv6yoCznCuih1wyPUdXe/R5X+I0+Z6WEov2P5EaotR7kfhC/RfAp9ZKaPMbiR0QNnddv2O1YHrLxHnbjTdQ5m97+ST3fWlynGVeljCp7NWud+UZ3TFPyAtc66U/acpoivXh14hBGIF122WJfz6roz/Kiy/z0/Kn9/5NVQIx4T5W7Qv2f1D1G9QVS3l8HRDG86sj7QrXd0x5Eu6663WF23prLuuoL/Zb+w/SM+EWleEW5k6tciPQ79/arFiw/wvXffiH8zjnX7/L5xcRrpX6heLtLrIg0vg3WofhvxqWhszxcP10477bTTTjvttGPZH2uDRhY="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "Bounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 16,
          width = 32,
          height = 992,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 292,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 16,
          width = 992,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 295,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 112,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 112,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 208,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 48,
          width = 32,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 304,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 308,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 400,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 309,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 400,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 310,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 496,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 311,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 592,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 592,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 313,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 112,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 314,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 112,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 315,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 112,
          width = 32,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 316,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 592,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 48,
          width = 32,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 304,
          width = 32,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 208,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 400,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 496,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 528,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 325,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 528,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 688,
          width = 448,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 112,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1072,
          y = 16,
          width = 32,
          height = 992,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 304,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 208,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 240,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 400,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 400,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 496,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 496,
          width = 32,
          height = 416,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 880,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 337,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 688,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 688,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 339,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 784,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 976,
          width = 992,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 880,
          width = 544,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 784,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 347,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 688,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 348,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 784,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 720,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 784,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 912,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "Bottle",
      visible = true,
      opacity = 1,
      offsetx = -8,
      offsety = -8,
      properties = {},
      objects = {
        {
          id = 487,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 490,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 502,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 504,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 505,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 508,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 509,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 512,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 518,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 519,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 526,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 527,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 528,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 529,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 534,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 539,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 541,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 542,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 543,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 545,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 547,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 549,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 554,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 555,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 556,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 558,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 559,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 560,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 563,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 564,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 566,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 568,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 569,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 570,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 571,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 572,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 573,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 574,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 575,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 576,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 577,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 578,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 580,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 581,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 582,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 583,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 584,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 585,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 586,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 587,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 588,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 589,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 590,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 591,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 592,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 593,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 594,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 595,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 596,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 597,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 598,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 599,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 600,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 601,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 603,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 604,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 605,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 606,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 607,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 608,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 609,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 610,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 611,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 615,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 616,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 617,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 618,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 619,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 620,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 621,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 622,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 623,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 624,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 625,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 626,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 627,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 628,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 629,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 630,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 631,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 632,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 633,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 634,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 635,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 636,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 637,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 638,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 639,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 641,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 642,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 643,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 644,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 645,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 646,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 647,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 648,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 649,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 650,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 651,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 652,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 653,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 654,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 655,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 657,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 658,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 659,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 660,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 661,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 662,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 663,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 664,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 665,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 666,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 667,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 668,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 669,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 670,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 671,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 672,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 673,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 674,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 675,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 676,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 677,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 678,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 679,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 680,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 681,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 682,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 683,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 684,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 685,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 686,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 687,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 688,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 689,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 690,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 692,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 693,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 694,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 695,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 696,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 697,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 698,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 699,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 700,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 701,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 702,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 703,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 704,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 705,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 706,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 707,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 708,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 709,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 710,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 711,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 712,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 714,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 715,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Blue",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 717,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 864,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 719,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 816,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 724,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 816,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 734,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 739,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 740,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 744,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 749,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 751,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 755,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 756,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 758,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 759,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 760,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 912,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 762,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 624,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 765,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 624,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 766,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 767,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 624,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 769,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 771,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 772,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 773,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 768,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 774,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 912,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Exit",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "Pink",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 944,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
