return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 67,
  height = 64,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 10,
  nextobjectid = 1078,
  properties = {},
  tilesets = {
    {
      name = "Tileset",
      firstgid = 1,
      filename = "Tileset.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 8,
      image = "Tileset.png",
      imagewidth = 128,
      imageheight = 64,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {
        {
          name = "Walls",
          tile = 0,
          properties = {}
        }
      },
      tilecount = 32,
      tiles = {
        {
          id = 0,
          terrain = { -1, -1, -1, 0 }
        },
        {
          id = 1,
          terrain = { -1, -1, 0, 0 }
        },
        {
          id = 2,
          terrain = { -1, -1, 0, -1 }
        },
        {
          id = 3,
          terrain = { 0, 0, 0, -1 }
        },
        {
          id = 4,
          terrain = { 0, 0, -1, -1 }
        },
        {
          id = 5,
          terrain = { 0, 0, -1, 0 }
        },
        {
          id = 8,
          terrain = { -1, 0, -1, 0 }
        },
        {
          id = 9,
          terrain = { 0, 0, 0, 0 }
        },
        {
          id = 10,
          terrain = { 0, -1, 0, -1 }
        },
        {
          id = 11,
          terrain = { 0, -1, 0, -1 }
        },
        {
          id = 13,
          terrain = { -1, 0, -1, 0 }
        },
        {
          id = 16,
          terrain = { -1, 0, -1, -1 }
        },
        {
          id = 17,
          terrain = { 0, 0, -1, -1 }
        },
        {
          id = 18,
          terrain = { 0, -1, -1, -1 }
        },
        {
          id = 19,
          terrain = { 0, -1, 0, 0 }
        },
        {
          id = 20,
          terrain = { -1, -1, 0, 0 }
        },
        {
          id = 21,
          terrain = { -1, 0, 0, 0 }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 67,
      height = 64,
      id = 1,
      name = "Floor",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztWEGOxCAM6wfmBzv//+ae9lJBcGIb0CoHqxJTkmAcU+bzPM+n0Wg0Gg0xfl6YjTvgzuXg4it6KnJl8qi5UPEw4qOSK5NHycVsPx09osz1fcXPcDHiko1b2Q82l0oX7zp2c8GsQVVzpIusbmd9h74/249qr7l0Efl4xMVoHrqGShynX7zXjvg2Mi+ji0wcpy4QjOZG/bV6n4nj0IVCU5k1Z9a2WxesplQcKbir7i0CVS9UNR/FUepi5VNRrahHzvJVdeG4j6DnZzQX4S6KneEiisFysYL6Wwh5P5tX8f2a8RQmzmhtqrzZ+Ke5cK6NrXNHj2TjqHuqwoXCOyv/taBrm/Gi1oXqTEV5yHCx4kOpC9e3Vlbbq/FsPawuds29MQ7DJbsPt8WZcZnRuvp8YXtNrYtZnRkPi+bN4mTfV/sFwgVS12x/1Hw4dcHoHLlfuuHWhYJH570gU8+O+agudnKh1EUFqC529YxKF1W/Q3Qxqtf1ZLhQ8JH1EScPLBeMHlFdnDhfdnkVsv+r8f8AVhen61f3CKOL23pkti7Gt6NxRa6d3uk+R5w8qM5UlSZRvbhwkzevdOGqldWFi4sT58hNPbLSKuIjJ3tkFMPl55Fe1DUwXLh4yOjihjPV4e033FNYXag8DNl/Zw0nvDcTc+UXN3AR9baqT0bjt/YIwkXFw9D7y99vDHZxwZwj6P2F5WOnLlwadsdvNBqNRkOJXxaeU1M="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 67,
      height = 64,
      id = 3,
      name = "Decorations",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztmttuhDAMRHmDN/r/X9tKW0S6SpRJxnZMd44UKULYhllPWC7bJoQQQthz/Iyv33EU289iu9WIrHVOaHEd13Wc5XYPomrN5JQWN0djXuay6uGWR6xqlb6Y7YuRuQdWtdg80qIfP9q3J7G/Vd0ILZg8TF2rPCjSoh/v0efI/h55UDx6IdscRVrUYxhfjPZwpHdQVq2Ro/szeVCkxY2VL6ximf9grEcQ2DVpNo/3/jN8ihbeHkHy7MU+O1ALuffPuHaiefbt1gTJ33smJC24Y/O+LiB59sa8lTPCI1l6ZFUeadGPf+/DKL8gsdEeueocG4bVb4vivXZKi/qc8QjjF2Q86ToS3SNWdaVFPcbq/iLSL8jxoFj9bpl7xDOml+epWni8187mlwhGz39Vj0Tw37R4f7/wyR654lh/ZeuF2euItHjBeITxi/d3jFnWo1U9knFtfqoWkb3q7Zcs9yNI/lU94hkzm/9JWnj36iq/oHj8PqPnn2X9lxY3rW/jkWe/SH8y33GNjtYzYZQrrvZ8feSdwEzd2pyldi4o0uJvbK2vGI8wPmIG6xEhhBAC4RvMa0AD"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 67,
      height = 64,
      id = 2,
      name = "Walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztWw1LAzEMnXMKogjT3f7/T3UDD0LIy8cl6Z3zHpS5mja9rs1rkt7hsGPHjh3L8HQrx1uZyOck1B1ZmVj9pBTeTmovyaDvnvHy+mfHXLzdyulWvlh5/a1/IYXLzIXLSPLa/7ku3qekW+pfGs/Lb/8fzrmQ5D6d7StwH8N7Y//eZ0Fz0T0+iu559z7Lf5gLb/93OemZH22PZNeFVE95B/GExhXS96uiC+lB/CPxhXcukByai/NB5wrEQRInUDuP1uZJkEdchvgCPYskV71HvL+DpSu6d7L9aJy6dA9Hn6GK15He7LrI2LMlz1C1LjJrvINHom2RfGU/Wdt5Oci+Bf2O7DbihYg8GpvWT2aNo/aUL5DPgez/ve03GBPipog8ejbUT2SPjNwLFfu/yo5IcmtzJ4LG911zMZIvHnVddI2JyndyrSQ384UWn0J2W2orxbru369gTDy2Rv0UtEcuQE+EpzhoXEuLRSH7fBJktTiT1Y/HTzkL+r4U+Wwsx4OMrfGMITq2Cn9klO3U+sn4EVY/I9ZFpi2F9gwj/ZHMuqiKR1X5h9k9op35rZxEJB6l5UlQP9wnkuJntGi8k7EXs21HeQ0Pv1h5E/q31M9ZkUd5luxcVOdHquzIEr0d9iLLL6PyCVxv5nftiHf+1XVR5f9Utc2gcy6or4Hy2NG4luWzaDl9lMOn/k4Hp1IbjngE+ReaDeLcJPGDtz4ynu64FkJVDKYK2fNFBh05lwyye6RD98h8NUU2V5RBVb6jChEekc78lg8w10XzHR7/ReIUxGeeT8Qv0vhm245sM6rT/JHIHuGcpeXmtZwNiqchP4Vj5B7Z2hmMo8N2bs1eROai43yxNU5d86z1F/eIFDuy7De6m+WJU6EYmnUvy7ovPNdl8iMSj3ju7lr+QiTfzXM0SK/GaUt4balcBbJ3iDJ6Mz57BzpiaF69a53BEbJ3iJZiTU7VdK21RyryI9a7GYhvIvepvHEw6y4A4ruIP2LFoNA7IMgn0PIdETtv3TH25l68749swXcY8c5E9l2akXOxlXdp1rBnI3Vlz1qPtC4iZy1694n6FFK95oto+QyJkyRdGm9Yd8IQz3h5BN3vtfIUGp9Y8SgUf/L6HsgX0fhN4q8dO3bs8OIHnH45Mg=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "Bounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 775,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 32,
          height = 896,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 776,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 880,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 778,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 779,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 112,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 781,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 336,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 782,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 256,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 783,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 192,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 784,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 352,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 785,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 256,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 786,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 96,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 788,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 352,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 789,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 480,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 790,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 448,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 791,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 640,
          width = 240,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 792,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 448,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 793,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 160,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 794,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 160,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 795,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 160,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 796,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 256,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 797,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 352,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 798,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 384,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 799,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 64,
          width = 32,
          height = 896,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 800,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 448,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 802,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 352,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 803,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 448,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 804,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 544,
          width = 176,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 806,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 544,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 807,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 544,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 809,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 736,
          width = 304,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 810,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 812,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 640,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 813,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 928,
          width = 880,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 814,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 736,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 815,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 736,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 816,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 832,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 817,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 832,
          width = 272,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 818,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 864,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 821,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 928,
          width = 880,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 822,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 864,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 823,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 832,
          width = 272,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 824,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 832,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 825,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 736,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 826,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 736,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 827,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 736,
          width = 304,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 828,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 640,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 829,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 640,
          width = 240,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 830,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 544,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 831,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 544,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 832,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 544,
          width = 176,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 833,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 480,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 834,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 448,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 835,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 448,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 836,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 448,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 837,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 448,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 838,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 384,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 839,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 840,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 352,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 841,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 352,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 842,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 352,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 843,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 352,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 844,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 256,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 845,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 256,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 846,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 256,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 847,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 112,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 848,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 192,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 849,
          name = "",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 160,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 850,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 160,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 851,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 160,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 852,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 336,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 853,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 96,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 854,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 855,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 64,
          width = 32,
          height = 896,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 856,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 880,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 857,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 32,
          height = 896,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "Bottle",
      visible = true,
      opacity = 1,
      offsetx = -8,
      offsety = -8,
      properties = {},
      objects = {
        {
          id = 858,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 859,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 860,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 863,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 864,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 866,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 867,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 868,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 869,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 870,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 871,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 872,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 873,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 874,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 875,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 876,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 877,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 878,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 879,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 880,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 881,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 882,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 883,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 884,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 885,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 886,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 887,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 888,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 889,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 890,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 891,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 892,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 893,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 894,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 895,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 896,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 897,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 898,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 899,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 900,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 902,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 903,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 904,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 905,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 907,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 908,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 909,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 910,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 912,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 913,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 914,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 915,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 916,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 917,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 918,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 919,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 920,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 921,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 922,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 923,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 924,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 925,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 926,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 927,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 928,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 929,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 930,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 931,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 932,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 934,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 935,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 936,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 937,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 938,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 939,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 940,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 941,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 943,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 945,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 946,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 947,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 949,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 950,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 951,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 953,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 954,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 955,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 956,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 957,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 958,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 959,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 960,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 961,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 962,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 963,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 964,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 965,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 966,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 967,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 968,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 969,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 464,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 970,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 971,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 512,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 972,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 973,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 974,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 975,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 976,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 977,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 752,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 978,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 560,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 979,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 656,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 980,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 981,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 982,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 983,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 984,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 985,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 986,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 987,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 988,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 989,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 990,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 991,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 992,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 993,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 995,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 996,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 997,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 998,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 999,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1000,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1001,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1002,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1003,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1004,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1005,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1006,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1007,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1008,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1010,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1011,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1012,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1013,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1014,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1015,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1016,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1017,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1018,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1019,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1020,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1021,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1022,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1023,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1024,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1025,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1026,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1027,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1028,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1029,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1030,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1031,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1032,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1033,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1034,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1035,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1036,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 896,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1037,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 800,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1038,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 848,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1039,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1040,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1041,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1042,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1043,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1044,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1045,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1046,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1047,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1048,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1050,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1051,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Blue",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1052,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1053,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1054,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1055,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1056,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1057,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1058,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1059,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1060,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1061,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1062,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1063,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 576,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1064,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 384,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 672,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1066,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 864,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1067,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 768,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1068,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 816,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1069,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 864,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1071,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 528,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1072,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 816,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1073,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 480,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1075,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1076,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1077,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Exit",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 400,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "Pink",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 819,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
